parameters:
- name: svcConnAzureRm
  type: string  
- name: region
  type: string
- name: env
  type: string
- name: dependsOn  
  type: object

stages:
- stage: ${{ parameters.region }}_${{ parameters.env }}
  displayName: ${{ parameters.region }}_${{ parameters.env }}
  variables: 
    - template: Variables/reg-env.yml 
      parameters:
        region: ${{ parameters.region }}
        env: ${{ parameters.env }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - deployment: Uninstall    
    displayName: Uninstall App Helm Release
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmDeploy@0
            displayName: 'Uninstall $(appName)'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: ${{ parameters.svcConnAzureRm}}
              azureResourceGroup: $(rgName)
              kubernetesCluster: $(aksName)
              command: 'uninstall'
              namespace: $(helmReleaseNamespace)
              arguments: '$(helmReleaseName) --debug'
  - deployment: Infrastructure    
    dependsOn: Uninstall
    displayName: Destroy App Specific Infra
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - template:  ../../../Common/Templates/reg-env-set-vars.yml        
            parameters:
              region: ${{ parameters.region }}
              env: ${{ parameters.env }}     
          - template: ../../../Common/Templates/replace-tokens.yml
            parameters:
              targetFiles: |
                Devops/App/Terraform/variables.tf              
          - template: ../../../Common/Templates/agent-sql-access.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
          - template: ../../../Common/Templates/tf-init-az.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/App/Terraform'
          - template: ../../../Common/Templates/tf-destroy-az.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/App/Terraform'