parameters:
- name: svcConnAzureRm
  type: string  
- name: region
  type: string
- name: env
  type: string
- name: dependsOn  
  type: object
- name: apply
  type: boolean

stages:
- stage: ${{ parameters.region }}_${{ parameters.env }}
  displayName: ${{ parameters.region }}_${{ parameters.env }}
  variables: 
    - template: Variables/reg-env.yml 
      parameters:
        region: ${{ parameters.region }}
        env: ${{ parameters.env }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - deployment: Approval
    displayName: 'Approval Required'
    condition: ne('${{ parameters.env }}', 'dev')
    environment: ${{ parameters.region }}_${{ parameters.env }}
    pool: server
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ManualValidation@0
            inputs:
              instructions: 'Please review the changes and approve or reject the deployment.'
              onTimeout: 'reject'
              timeoutInMinutes: 1440
              notifyUsers: none
  - deployment: Infrastructure    
    dependsOn: Approval
    condition: eq('${{ parameters.apply }}', 'true')
    displayName: Ensure App Specific Infra
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true           
          - template:  ../../../Common/Templates/stampSetVars.yml        
            parameters:
              region: ${{ parameters.region }}
              env: ${{ parameters.env }}                   
          - template: ../../../Common/Templates/replace-tokens.yml
            parameters:
              targetFiles: Devops/App/Terraform/variables.tf
          - template: ../../../Common/Templates/agent-sql-access.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
          - template: ../../../Common/Templates/tf-init-az.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/App/Terraform'
          - template: ../../../Common/Templates/tf-apply-az.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/App/Terraform'  
  - deployment: Deploy    
    dependsOn: Infrastructure
    condition: in(dependencies.Infrastructure.result, 'Succeeded', 'Skipped')
    displayName: Deploy Application
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - template:  ../../../Common/Templates/reg-env-set-vars.yml        
            parameters:
              region: ${{ parameters.region }}
              env: ${{ parameters.env }}      
          - task: AzureCLI@2
            displayName: Get Azure Managed Workload Identities
            inputs:
              azureSubscription: ${{ parameters.svcConnAzureRm}}
              scriptType: bash
              scriptLocation: 'inlineScript'
              inlineScript: |
                aksManagedIdentities=$(az identity list -g $(rgName) --query "[?starts_with(name,'$(aksWorkloadIdentityNamePrefix)')].{client_id: clientId, name: name}" -o json | jq -c '.')
                echo "##vso[task.setvariable variable=aksManagedIdentities;]$aksManagedIdentities"
                echo $replace-tokens
          - template: ../../../Common/Templates/replace-tokens.yml
            parameters:
              targetFiles: |
                Devops/App/Helm/**/Chart.yaml
                Devops/App/Helm/**/values.yaml            
          - template: ../../../Common/Templates/helm-upgrade.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              releaseName: $(helmReleaseName)
              chartPath: '$(System.DefaultWorkingDirectory)/Devops/App/Helm/$(appName)'
              namespace: $(helmReleaseNamespace)