imageTag: latest
tenants: 
  - tenant1
  - tenant2
storageClassBlobName: "azureblob-nfs-standard"
pvcBlobName: "azure-blob"

# dynamic values
aksNamespace: "default"
workloadIdentityServiceAccountName: ""
workloadIdentityClientId: "dynamic"
keyVaultName: "dynamic"
azureContainerRegistryName: "dynamic"
