imageTag: #{imageTag}#
tenants: #{tenantsYaml}#
storageClassBlobName: #{aksStorageClassBlobName}#
pvcBlobName: #{aksPvcBlobName}#
aksNamespace: #{aksNamespace}#
workloadIdentityServiceAccountName: #{aksWorkloadIdentityServiceAccountName}#
workloadIdentityClientId: #{aksWorkloadIdentityClientId}#
keyVaultName: #{kvName}#
azureContainerRegistryName: #{acrName}#