# persistent volume claim for common storage class container
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcBlobName }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassBlobName }}
  resources:
    requests:
      storage: 5Gi
---
# persistent volume claim for tenant1 storage class container
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcBlobNameTenant1 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassBlobNameTenant1 }}
  resources:
    requests:
      storage: 5Gi
---
# persistent volume claim for tenant2 storage class container
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcBlobNameTenant2 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassBlobNameTenant2 }}
  resources:
    requests:
      storage: 5Gi