# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/AksWorkloadIdentitySample.Api/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)   
    - task: TerraformTaskV3@3
      displayName: Terraform Init - Infrastructure
      inputs:
        provider: 'azurerm'
        backendServiceArm: 'Keith Patton - VS Professional Sub'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/Infrastructure'
        backendAzureRmResourceGroupName: 'rg-terraform'