# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Infrastructure
  displayName: Ensure Infrastructure
  jobs:
  - job: Terraform
    displayName: Ensure Azure Resources
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformTaskV3@3
      displayName: Terraform Init 
      inputs:
        provider: 'azurerm'
        backendServiceArm: 'Keith Patton - VS Professional Sub'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/Infrastructure'
        backendAzureRmResourceGroupName: 'rg-terraform'
        backendAzureRmStorageAccountName: 'terraformstateakssample'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'
    - task: AzureCLI@2
      displayName: Az Cli Login
      inputs:
        azureSubscription: 'Keith Patton - VS Professional Sub'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az --version
          az account show
    - task: TerraformTaskV3@3
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        environmentServiceNameAzureRM: 'Keith Patton - VS Professional Sub'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/Infrastructure'
        commandOptions: '-auto-approve -var-file="../shared.tfvars" -var-file="../infra.tfvars"'
        backendAzureRmResourceGroupName: 'rg-terraform'
        backendAzureRmStorageAccountName: 'terraformstateakssample'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    condition: eq(1,2)
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/AksWorkloadIdentitySample.Api/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)   
