# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/AksWorkloadIdentitySample.Api/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)   
- stage: Infra
  displayName: Ensure infrastructure
  jobs:
  - job: Terraform
    displayName: Use Terraform to ensure infrastructure is ready for the deploy stage
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformTaskV3@3
      displayName: Terraform Init 
      inputs:
        provider: 'azurerm'
        backendServiceArm: 'Keith Patton - VS Professional Sub'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: TerraformTaskV3@3
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        backendServiceArm: 'Keith Patton - VS Professional Sub'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/Infrastructure'
        commandOptions: '-auto-approve -var-file="..\shared.tfvars" -var-file="..\infra.tfvars"'
        environmentServiceNameAzureRM: 'Keith Patton - VS Professional Sub'
        backendAzureRmResourceGroupName: 'rg-terraform'
        backendAzureRmStorageAccountName: 'terraformstateakssample'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'
