# 1. Ensure Infrastructure
# 2. Build and Push Image
# 4. Deploy Image

trigger: none
#- master

resources:
- repo: self

variables:
  appName: 'aksdemo' 
  location: 'australiaeast'
  svcConnAzureRm: 'Keith Patton - VS Professional Sub'
  uniqueSuffix: 'qpe'
  acrName: 'acr$(appName)$(uniqueSuffix)'
  imageName: 'aksworkloadidentitysampleapi'
  imageTagName: 'latest'
  aksResourceGroup: 'rg-$(appName)'
  aksClusterName: 'aks-$(appName)'
  aksWorkloadIdentityServiceAccountName: 'sa-workload-identity-$(appName)'
  aksNamespace: 'default'
  aksWorkloadIdentityName: 'aks-$(appName)'
  aksWorkloadIdentityClientId: '{dynamic}'
  aksNodeCount: 1
  aksVmSize: 'Standard_B2s'
  helmReleaseName: 'aks-sample'
  helmChartVersion: '0.4.0'
  kvName: 'kv-$(appName)-$(uniqueSuffix)'
  tag: '$(Build.BuildId)'
  tfStateResourceGroup: 'rg-terraform'
  tfStateStorageAccount: 'terraformstateakssample'
  tfStateContainerName: 'tfstate'
  tfStateFileName: 'terraform.tfstate'

stages:
- stage: Infrastructure
  displayName: Ensure Infrastructure
  jobs:
  - job: Terraform
    displayName: Ensure Azure Resources
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformTaskV3@3
      displayName: Terraform Init 
      inputs:
        provider: 'azurerm'
        backendServiceArm: $(svcConnAzureRm)
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/Infrastructure'
        backendAzureRmResourceGroupName: $(tfStateResourceGroup)
        backendAzureRmStorageAccountName: $(tfStateStorageAccount)
        backendAzureRmContainerName: $(tfStateContainerName)
        backendAzureRmKey: $(tfStateFileName)
    - task: TerraformTaskV3@3
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        environmentServiceNameAzureRM: $(svcConnAzureRm)
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/Infrastructure'
        commandOptions: "
          --auto-approve
          -var app_name=$(appName)
          -var location=$(location)
          -var unique_suffix=$(uniqueSuffix)
          -var aks_vm_size=$(aksVmSize)
          -var aks_node_count=$(aksNodeCount)
          -var aks_namespace=$(aksNamespace)"
        backendAzureRmResourceGroupName: $(tfStateResourceGroup)
        backendAzureRmStorageAccountName: $(tfStateStorageAccount)
        backendAzureRmContainerName: $(tfStateContainerName)
        backendAzureRmKey: $(tfStateFileName)
- stage: Image
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        repository: $(imageName)
        dockerfile: '$(Build.SourcesDirectory)/AksWorkloadIdentitySample.Api/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: $(imageTagName)
    - task: AzureCLI@2
      displayName: 'Push Image'
      inputs:
        azureSubscription: $(svcConnAzureRm)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(acrName)
          docker tag $(imageName):$(imageTagName) $(acrName).azurecr.io/$(imageName):$(imageTagName)
          docker push $(acrName).azurecr.io/$(imageName):$(imageTagName)
- stage: Deploy
  displayName: Deploy Application
  jobs:
  - job: Deploy
    displayName: Deploy Application
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: 'Get Azure Resoure Values'
      inputs:
        azureSubscription: $(svcConnAzureRm)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $aksWorkloadIdentityClientId = (az identity show --resource-group $(aksResourceGroup) --name $(aksWorkloadIdentityName) --query 'clientId' -otsv)
          Write-Output("##vso[task.setvariable variable=aksWorkloadIdentityClientId;]$aksWorkloadIdentityClientId")
    - task: HelmDeploy@0
      displayName: 'Deploy Chart'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: $(svcConnAzureRm)
        azureResourceGroup: $(aksResourceGroup)
        kubernetesCluster: $(aksClusterName)
        namespace: $(aksNamespace)
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: '$(System.DefaultWorkingDirectory)/Terraform/Deploy/aks-sample'
        chartVersion: $(helmChartVersion)
        releaseName: $(helmReleaseName)
        overrideValues: '
          aksNamespace=$(aksNamespace),
          workloadIdentityServiceAccountName=$(aksWorkloadIdentityServiceAccountName),
          keyVaultName=$(kvName),
          azureContainerRegistryName=$(acrName),
          workloadIdentityClientId=$(aksWorkloadIdentityClientId)'
        arguments: '--install --atomic'