parameters:
- name: svcConnAzureRm
  type: string  
- name: tenants
  type: object  
- name: rings
  type: object  
- name: region
  type: string
- name: env
  type: string
- name: dependsOn  
  type: object
- name: imageBuild
  type: boolean
- name: imageBuildTag
  type: string
- name: apply
  type: boolean

stages:
- stage: ${{ parameters.region }}_${{ parameters.env }}
  displayName: ${{ parameters.region }}_${{ parameters.env }}
  variables: 
    - template: variables/reg-env.yml 
      parameters:
        region: ${{ parameters.region }}
        env: ${{ parameters.env }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - deployment: Image
    displayName: Build and Push Images
    condition: and(succeeded(), eq('${{ parameters.imageBuild }}', 'true'))
    # for security reasons all environments must be provisioned by authorised person in advance
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - task: Docker@2
            displayName: Build App Image
            inputs:
              command: build
              repository: $(imageName)
              dockerfile: '$(Build.SourcesDirectory)/AksWorkloadIdentitySample.Api/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: ${{ parameters.imageBuildTag }}
          - task: Docker@2
            displayName: Build Job Init Image
            inputs:
              command: build
              repository: "$(jobInitImageName)"
              dockerfile: '$(Build.SourcesDirectory)/AksSample.Job/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: $(jobInitImageVersion)
          - task: AzureCLI@2
            displayName: 'Push Images'
            inputs:
              azureSubscription: ${{ parameters.svcConnAzureRm}}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az acr login --name $(acrName)
                # push app image
                docker tag $(imageName):${{ parameters.imageBuildTag }} $(acrName).azurecr.io/$(imageName):${{ parameters.imageBuildTag }}
                docker push $(acrName).azurecr.io/$(imageName):${{ parameters.imageBuildTag }}  
                # push job init
                docker tag $(jobInitImageName):$(jobInitImageVersion) $(acrName).azurecr.io/$(jobInitImageName):$(jobInitImageVersion)
                docker push $(acrName).azurecr.io/$(jobInitImageName):$(jobInitImageVersion)                                    

  - deployment: Infrastructure    
    dependsOn: Image
    condition: and(eq('${{ parameters.apply }}', 'true'), in(dependencies.Image.result, 'Succeeded', 'Skipped'))
    displayName: Ensure App Specific Infra
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - template:  ../../Common/Templates/stampSetVars.yml        
            parameters:
              tenants: ${{ parameters.tenants }}
              rings: ${{ parameters.rings }}
              region: ${{ parameters.region }}
              env: ${{ parameters.env }}                   
          - template: ../../Common/Templates/replaceTokens.yml
            parameters:
              targetFiles: Devops/App/Terraform/variables.tf
          - template: ../../Common/Templates/buildAgentSqlAccess.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
          - template: ../../Common/Templates/tfInitAzRm.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/App/Terraform'
          - template: ../../Common/Templates/tfApplyAzRm.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/App/Terraform'  
  - deployment: Deploy    
    dependsOn: Infrastructure
    condition: and(in(dependencies.Image.result, 'Succeeded', 'Skipped'), in(dependencies.Infrastructure.result, 'Succeeded', 'Skipped'))
    displayName: Deploy Application
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - template:  ../../Common/Templates/stampSetVars.yml        
            parameters:
              tenants: ${{ parameters.tenants }}
              rings: ${{ parameters.rings }}
              region: ${{ parameters.region }}
              env: ${{ parameters.env }}      
          - task: AzureCLI@2
            displayName: Get Azure Managed Workload Identities
            inputs:
              azureSubscription: ${{ parameters.svcConnAzureRm}}
              scriptType: bash
              scriptLocation: 'inlineScript'
              inlineScript: |
                aksManagedIdentities=$(az identity list -g $(rgName) --query "[?starts_with(name,'$(aksWorkloadIdentityNamePrefix)')].{client_id: clientId, name: name}" -o json | jq -c '.')
                echo "##vso[task.setvariable variable=aksManagedIdentities;]$aksManagedIdentities"
                echo $aksManagedIdentities
          - template: ../../Common/Templates/replaceTokens.yml
            parameters:
              targetFiles: |
                Devops/App/Helm/**/Chart.yaml
                Devops/App/Helm/**/values.yaml            
          - template: ../../Common/Templates/helmUpgrade.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              releaseName: $(helmReleaseName)
              chartPath: '$(System.DefaultWorkingDirectory)/Devops/App/Helm/$(appName)'
              namespace: $(helmReleaseNamespace)