parameters:
- name: svcConnAzureRm
  type: string  
- name: tenants
  type: object  
- name: rings
  type: object  
- name: region
  type: string
- name: env
  type: string
- name: dependsOn  
  type: object
- name: apply
  type: boolean

stages:
- stage: ${{ parameters.region }}_${{ parameters.env }}
  displayName: ${{ parameters.region }}_${{ parameters.env }}
  variables: 
    - template: variables/reg-env.yml 
      parameters:
        region: ${{ parameters.region }}
        env: ${{ parameters.env }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - deployment: Infrastructure    
    condition: and(eq('${{ parameters.apply }}', 'true'), in(dependencies.Image.result, 'Succeeded', 'Skipped'))
    displayName: Ensure App Specific Infra
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - script: |
              echo $(resources.pipeline.build_and_package.pipelineID)
              echo $(resources.pipeline.build_and_package.runName)
              echo $(resources.pipeline.build_and_package.runID)
              echo $(resources.pipeline.build_and_package.runURI)
              echo $(resources.pipeline.build_and_package.sourceBranch)
              echo $(resources.pipeline.build_and_package.sourceCommit)
              echo $(resources.pipeline.build_and_package.sourceProvider)
              echo $(resources.pipeline.build_and_package.requestedFor)
              echo $(resources.pipeline.build_and_package.requestedForID)            
          - template:  ../../Common/Templates/stampSetVars.yml        
            parameters:
              tenants: ${{ parameters.tenants }}
              rings: ${{ parameters.rings }}
              region: ${{ parameters.region }}
              env: ${{ parameters.env }}                   
          - template: ../../Common/Templates/replaceTokens.yml
            parameters:
              targetFiles: Devops/App/Terraform/variables.tf
          - template: ../../Common/Templates/buildAgentSqlAccess.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
          - template: ../../Common/Templates/tfInitAzRm.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/App/Terraform'
          - template: ../../Common/Templates/tfApplyAzRm.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/App/Terraform'  
  - deployment: Deploy    
    dependsOn: Infrastructure
    condition: and(in(dependencies.Image.result, 'Succeeded', 'Skipped'), in(dependencies.Infrastructure.result, 'Succeeded', 'Skipped'))
    displayName: Deploy Application
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - template:  ../../Common/Templates/stampSetVars.yml        
            parameters:
              tenants: ${{ parameters.tenants }}
              rings: ${{ parameters.rings }}
              region: ${{ parameters.region }}
              env: ${{ parameters.env }}      
          - task: AzureCLI@2
            displayName: Get Azure Managed Workload Identities
            inputs:
              azureSubscription: ${{ parameters.svcConnAzureRm}}
              scriptType: bash
              scriptLocation: 'inlineScript'
              inlineScript: |
                aksManagedIdentities=$(az identity list -g $(rgName) --query "[?starts_with(name,'$(aksWorkloadIdentityNamePrefix)')].{client_id: clientId, name: name}" -o json | jq -c '.')
                echo "##vso[task.setvariable variable=aksManagedIdentities;]$aksManagedIdentities"
                echo $aksManagedIdentities
          - template: ../../Common/Templates/replaceTokens.yml
            parameters:
              targetFiles: |
                Devops/App/Helm/**/Chart.yaml
                Devops/App/Helm/**/values.yaml            
          - template: ../../Common/Templates/helmUpgrade.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              releaseName: $(helmReleaseName)
              chartPath: '$(System.DefaultWorkingDirectory)/Devops/App/Helm/$(appName)'
              namespace: $(helmReleaseNamespace)