parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
  default: au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev
- name: rings
  displayName: 'Deployment Rings'
  type: object
  default: 
    - name: stable
      version: "0.2.1"
    - name: vnext
      version: "0.2.2"      
variables:
  - name: ringsJson
    value: '${{ convertToJson(parameters.rings) }}'
  - name: appVersion: 
    value: "0.2.1"
  - name: imageName
    value: '$(appName)'
  - name: imageTag
    value: '$(appVersion)'
  - name: aksWorkloadIdentityClientId
    value: '{dynamic}'
  - name: aksPvcBlobName
    value: 'azure-blob'
  - name: aksStorageClassBlobName
    value: 'azureblob-nfs-standard'
  - name: webapiChartDescription 
    value: 'AKS Sample App'
  - name: webapiReleaseName
    value: 'aks-sample'
  - name: webapiChartName
    value: 'aks-sample'  
  - name: webapiChartVersion
    value: '0.7.2'
  - name: webapiAppVersion
    value: '$(appVersion)'