parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
  default: au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev

variables:
  appVersion: "0.1.9"
  imageName: '$(appName)'
  imageTag: '$(appVersion)'
  aksWorkloadIdentityClientId: '{dynamic}'
  aksPvcBlobName: 'azure-blob'
  aksStorageClassBlobName: 'azureblob-nfs-standard'
  webapiChartDescription: 'AKS Sample App'
  webapiReleaseName: 'aks-sample'
  webapiChartName: 'aks-sample'  
  webapiChartVersion: '0.7.1'
  webapiAppVersion: '$(appVersion)'