parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
  default: au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev

variables:
  appVersion: "0.1.8"
  imageName: '$(appName)'
  imageTag: '$(appVersion)'
  aksWorkloadIdentityClientId: '{dynamic}'
  aksPvcBlobName: 'azure-blob'
  aksStorageClassBlobName: 'azureblob-nfs-standard'
  helmChartDescription: 'AKS Sample App'
  helmReleaseName: 'aks-sample'
  helmChartName: 'aks-sample'  
  helmChartVersion: '0.6.6'
  helmAppVersion: '$(appVersion)'