parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev
- name: rings
  displayName: 'Deployment Rings'
  type: object 
- name: imageBuildTag
  displayName: 'Image Build Tag'
  type: string
variables:
  - name: ringsJson
    value: '${{ convertToJson(parameters.rings) }}'
  - name: imageName
    value: '$(appName)'
  - name: imageBuildTag
    value: '{{ parameters.imageBuildTag }}'
  - name: aksWorkloadIdentityClientId
    value: '{dynamic}'
  - name: aksPvcBlobName
    value: 'azure-blob'
  - name: aksStorageClassBlobName
    value: 'azureblob-nfs-standard'
  - name: webapiChartDescription 
    value: 'AKS Sample App'
  - name: webapiReleaseName
    value: 'webapi'
  - name: webapiChartName
    value: 'webapi'  
  - name: webapiChartVersion
    value: '0.7.2'