name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
- repo: self

parameters:
- name: tenants
  displayName: 'Tenants'
  type: object
  default:
    - name: tenant1
      region: au1
      env: dev
    - name: tenant2
      region: au1
      env: dev    
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true

stages:
- template: ../Templates/stage.yml
  parameters:
    svcConnAzureRm: 'Keith Patton - VS Professional Sub'
    tenants: ${{ parameters.tenants }}
    region: 'au1'
    env: 'dev'
    dependsOn: []
    apply: ${{ parameters.apply }}