# 1. Ensure Infrastructure

trigger: none

resources:
- repo: self

variables:
- template: ../../Common/Templates/variables.yml  
- template: ../Templates/variables.yml

stages:
- stage: Infrastructure
  displayName: Ensure Infrastructure
  jobs:
  - job: Infrastructure
    displayName: Ensure Azure Resources
    pool:
      vmImage: ubuntu-latest
    steps:    
    - task: AzureCLI@2
      displayName: 'Enable Workload Identity Preview Feature'
      inputs:
        azureSubscription: $(svcConnAzureRm)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az extension add --name aks-preview
          az feature register --namespace "Microsoft.ContainerService" --name "EnableWorkloadIdentityPreview"
          az provider register --namespace Microsoft.ContainerService
    - task: AzureCLI@2
      displayName: 'Ensure Terraform State Storage Account and Container'
      inputs:
        azureSubscription: $(svcConnAzureRm)
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --location $(location) --name $(tfStateResourceGroup)
          az storage account create -n $(tfStateStorageAccount) -g $(tfStateResourceGroup) -l $(location) --sku Standard_LRS
          az storage container create -n $(tfStateContainerName) --account-name $(tfStateStorageAccount) -g $(tfStateResourceGroup)
    - task: replacetokens@5
      displayName: 'Replace tokens with variables'
      inputs:
        targetFiles: |
          **/variables.tf
        encoding: 'auto'
        tokenPattern: 'default'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'warn'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true   
        verbosity: 'detailed'   
    - task: TerraformTaskV3@3
      displayName: Terraform Init 
      inputs:
        provider: 'azurerm'
        backendServiceArm: $(svcConnAzureRm)
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/Infra/Terraform'
        backendAzureRmResourceGroupName: $(tfStateResourceGroup)
        backendAzureRmStorageAccountName: $(tfStateStorageAccount)
        backendAzureRmContainerName: $(tfStateContainerName)
        backendAzureRmKey: $(tfStateFileName)
    - task: TerraformTaskV3@3
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        environmentServiceNameAzureRM: $(svcConnAzureRm)
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/Infra/Terraform'
        commandOptions: 
          --auto-approve
        backendAzureRmResourceGroupName: $(tfStateResourceGroup)
        backendAzureRmStorageAccountName: $(tfStateStorageAccount)
        backendAzureRmContainerName: $(tfStateContainerName)
        backendAzureRmKey: $(tfStateFileName)