name: $(Date:yyyyMMdd)$(Rev:.r)_${{ parameters.region }}_${{ parameters.env }}

trigger: none

resources:
- repo: self

parameters:
- name: tenants
  displayName: 'All Tenants'
  type: object
  default:
    - name: tenant1
    - name: tenant2
- name: region
  displayName: 'Target Region'
  type: string
  values:
  - au1
  default: au1
- name: env
  displayName: 'Target Environment'
  type: string
  values:
  - dev
  default: dev  
- name: destroy
  displayName: 'Destroy Infra (Before Apply)'
  type: boolean
  default: false
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true

variables:
- template: ../../Common/Templates/variables.yml  
  parameters:
    tenants: ${{ parameters.tenants }} # filter the tenants based on a var which defines tenancy per region/env/ring
    #region: ${{ parameters.region }}
    #env: ${{ parameters.env }}
- template: ../Templates/variables.yml
  parameters:
    region: ${{ parameters.region }}
    env: ${{ parameters.env }}

stages:
- template: ../Templates/stage.yml
  parameters:
    regionStage: 'au1'
    envStage: 'dev'
    regionTarget: ${{ parameters.region }}
    envTarget: ${{ parameters.env }}
    dependsOn: []
    apply: ${{ parameters.apply }}
    destroy: ${{ parameters.destroy }}