name: $(Date:yyyyMMdd)$(Rev:.r)_${{ parameters.region }}_${{ parameters.env }}

trigger: none

resources:
- repo: self

parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
  default: au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev
  default: dev  
- name: tenants
  displayName: 'Tenants'
  type: object
  default:
    - name: tenant1
    - name: tenant2
- name: destroy
  displayName: 'Destroy Infra (Before Apply)'
  type: boolean
  default: false
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true

variables:
- template: ../../Common/Templates/variables.yml  
  parameters:
      tenants: ${{ parameters.tenants }}
      region: ${{ parameters.region }}
      env: ${{ parameters.env }}
- template: ../Templates/variables.yml
  parameters:
    region: ${{ parameters.region }}
    env: ${{ parameters.env }}

- name: region
  value: ${{ parameters.region }}
- name: env
  value: ${{ parameters.env }}

stages:
- stage: au1_dev
  condition: and(eq(variables['region'], 'au1'), eq(variables['env'], 'dev'))
  displayName: au1-dev
  pool:
    vmImage: ubuntu-latest 
  jobs:
   - template: ../Templates/jobs.yml