name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
- repo: self

parameters:
- name: tenantsAll
  displayName: 'Tenants'
  type: object
  default:
    - name: tenant1
      region: au1
      envs: 
        - dev
    - name: tenant2
      region: au1
      envs: 
        - dev            
  
- name: destroy
  displayName: 'Destroy Infra (Before Apply)'
  type: boolean
  default: false
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true

variables:
- template: ../../Common/Templates/variables/global.yml  
  parameters:
    tenantsAll: ${{ parameters.tenantsAll }} 

stages:
- template: ../Templates/stage.yml
  parameters:
    svcConnAzureRm: 'Keith Patton - VS Professional Sub'
    region: 'au1'
    env: 'dev'
    dependsOn: []
    apply: ${{ parameters.apply }}
    destroy: ${{ parameters.destroy }}
