name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
- repo: self

variables: 
  - template: templates/variables/root.yml    

stages:

- template: templates/stages/common-stage.yml
  parameters:
    dependsOn: []

- template: templates/stages/reg-env-stage.yml
  parameters:
    region: 'au1'
    env: 'dev'
    dependsOn: [common]

- template: templates/stages/reg-env-stage.yml
  parameters:
    region: 'au1'
    env: 'qa'
    dependsOn: [common]