name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
- repo: self

variables: 
  - template: templates/variables/root.yml

stages:

- template: templates/stages/reg-env-stage-teardown.yml
  parameters:
    region: 'au1'
    env: 'dev'
    dependsOn: []

- template: templates/stages/reg-env-stage-teardown.yml
  parameters:
    region: 'au1'
    env: 'qa'
    dependsOn: []

- template: templates/stages/common-stage-teardown.yml
  parameters:
    region: 'au1'
    env: 'dev'
    dependsOn: [au1_dev,au1_qa]