# Ensures that current build agent has pinholed access to the Azure Sql Server to perform tasks
# Note: Assumes sql variables already set up

parameters:
- name: svcConnAzureRm
  type: string

steps:
- task: AzureCLI@2
  displayName: 'Ensure Build Agent Sql Access'
  continueOnError: true
  inputs:
    azureSubscription: ${{ parameters.svcConnAzureRm}}
    addSpnToEnvironment: true
    scriptType: bash
    scriptLocation: 'inlineScript'
    inlineScript: |
      build_agent_ip=$(curl https://ipv4.icanhazip.com/)
      az sql server firewall-rule create -g $(rgName) --name "$(sqlFirewallRuleBuildAgentName)-pipeline" --server $(sqlServerName) --start-ip-address $build_agent_ip --end-ip-address $build_agent_ip