# Carries out a Helm Upgrade
# Note: Assumes file path chart and that resource group and cluster variables are already set up

parameters:
- name: svcConnAzureRm
  type: string
- name: releaseName
  type: string
- name: namespace
  type: string
- name: chartPath
  type: string

steps:
- task: HelmDeploy@0
  displayName: 'Deploy ${{ parameters.releaseName }}'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: ${{ parameters.svcConnAzureRm }}
    azureResourceGroup: $(rgName)
    kubernetesCluster: $(aksName)
    namespace: ${{ parameters.namespace }}
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: '${{ parameters.chartPath }}'
    releaseName: ${{ parameters.releaseName }}
    arguments: '--debug --atomic --reset-values --create-namespace'