# Sets $tenantsJson var to represent active tenants data for a particular stage (region and environment)

parameters:
- name: tenants
  displayName: 'Tenants'
  type: object
- name: region
  type: string
- name: env
  type: string

steps:
- task: Bash@3
  displayName: 'Sets Tenants Json Stage Var'
  inputs:
    targetType: 'inline'
    script: |
      region=$(echo "${{parameters.region}}")
      env=$(echo "${{parameters.env}}")
      allTenantsJson=$(echo '${{ convertToJson(parameters.tenants) }}')
      echo $allTenantsJson
      tenantsJson=$(echo '$allTenantsJson' | jq -c --arg region "$region" --arg env "$env" '[.[] | select(.region == $region) | select(.env == $env)]')
      echo "##vso[task.setvariable variable=tenantsJson;]$tenantsJson"
      echo $tenantsJson