# Sets $tenantsJson and $ringsJson vars to represent active 
# tenants and rings data for a particular stage (region and environment)

parameters:
- name: tenants
  type: object
- name: rings
  type: object
  default: []
- name: region
  type: string
- name: env
  type: string

steps:
- task: Bash@3
  displayName: 'Sets Tenants and Rings Json Stage Vars'
  inputs:
    targetType: 'inline'
    script: |
      region=$(echo "${{parameters.region}}")
      env=$(echo "${{parameters.env}}")
      allTenantsJson=$(echo '${{ convertToJson(parameters.tenants) }}')
      echo $allTenantsJson
      tenantsJson=$(echo "$allTenantsJson" | jq -c --arg region "$region" --arg env "$env" '[.[] | select(.region == $region) | select(.env == $env)]')
      echo "##vso[task.setvariable variable=tenantsJson;]$tenantsJson"
      echo $tenantsJson

      allRingsJson=$(echo '${{ convertToJson(parameters.rings) }}')
      echo $allRingsJson
      ringsJson=$(echo "$allRingsJson" | jq -c --arg region "$region" --arg env "$env" '[.[] | select(.region == $region) | select(.env == $env)]')
      echo "##vso[task.setvariable variable=ringsJson;]$ringsJson"
      echo $ringsJson