# common variables

parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev
- name: tenants
  displayName: 'Tenant List'
  type: object

variables:
- template: region/${{ parameters.region }}/variables.yml 
- template: env/${{ parameters.env }}/variables.yml  
- template: region-env/${{ parameters.region }}-${{ parameters.env }}/variables.yml  

- name: appName
  value: 'aksdemo'
- name: tenantsJson
  value: '${{ convertToJson(parameters.tenants) }}'
- name: rgName
  value: 'rg-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: acrName
  value: 'acr${{ parameters.region }}${{ parameters.env }}$(appName)$(uniqueSuffix)'
- name: kvName
  value: 'kv-${{ parameters.region }}-${{ parameters.env }}-$(appName)-$(uniqueSuffix)'
- name: aksName
  value: 'aks-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: aksNamespace
  value: 'default'
- name: aksStorageAccountName
  value: 'stg${{ parameters.region }}${{ parameters.env }}$(appName)aks'
- name: aksWorkloadIdentityName
  value: 'aks-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: aksWorkloadIdentityServiceAccountName
  value: 'sa-workload-identity-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: sqlServerName
  value: 'sql-${{ parameters.region }}-${{ parameters.env }}-$(uniqueSuffix)'