# common variables

parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
  default: au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev
- name: tenants
  displayName: 'Tenant List'
  type: object
  default: 
    - tenant1
    - tenant2

variables:
- template: region-env/${{ parameters.region }}-${{ parameters.env }}/variables.yml  
- template: region/${{ parameters.region }}/variables.yml 
- template: env/${{ parameters.env }}/variables.yml  
- name: appName
  value: 'aksdemo'
- name: tenantsJson
  value: '${{ convertToJson(parameters.tenants) }}'
- name: rgName
  value: 'rg-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: acrName
  value: 'acr${{ parameters.region }}${{ parameters.env }}$(appName)$(uniqueSuffix)'
- name: kvName
  value: 'kv-${{ parameters.region }}-${{ parameters.env }}-$(appName)-$(uniqueSuffix)'
- name: aksName
  value: 'aks-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: aksNamespace
  value: '$(appName)'
- name: aksWorkloadIdentityName
  value: 'aks-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: aksWorkloadIdentityServiceAccountName
  value: 'sa-workload-identity-${{ parameters.region }}-${{ parameters.env }}-$(appName)'