# common variables

parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
  default: au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev
- name: tenants
  displayName: 'Tenant List'
  type: object
  default: 
    - tenant1
    - tenant2

variables:
- template: region-env/${{ parameters.region }}-${{ parameters.env }}/variables.yml  
- template: region/${{ parameters.region }}/variables.yml 
- template: env/${{ parameters.env }}/variables.yml  
  appName: 'aksdemo'
  tenantsJson: '${{ convertToJson(parameters.tenants) }}'
  rgName: 'rg-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
  acrName: 'acr${{ parameters.region }}${{ parameters.env }}$(appName)$(uniqueSuffix)'
  kvName: 'kv-${{ parameters.region }}-${{ parameters.env }}-$(appName)-$(uniqueSuffix)'
  aksName: 'aks-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
  aksNamespace: '$(appName)'
  aksWorkloadIdentityName: 'aks-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
  aksWorkloadIdentityServiceAccountName: 'sa-workload-identity-${{ parameters.region }}-${{ parameters.env }}-$(appName)'