parameters:
- name: tenants
  displayName: 'Tenant List'
  type: object

variables:
  appName: 'aksdemo'
  location: 'australiaeast'
  tenantsJson: '${{ convertToJson(parameters.tenants) }}'
  svcConnAzureRm: 'Keith Patton - VS Professional Sub'
  uniqueSuffix: 'qpe'
  acrName: 'acr$(appName)$(uniqueSuffix)'
  rgName: 'rg-$(appName)'
  aksName: 'aks-$(appName)'
  aksWorkloadIdentityName: 'aks-$(appName)'
  aksWorkloadIdentityServiceAccountName: 'sa-workload-identity-$(appName)'
  aksNamespace: 'default'
  kvName: 'kv-$(appName)-$(uniqueSuffix)'