variables:
  appName: 'aksdemo'
  location: 'australiaeast'
  svcConnAzureRm: 'Keith Patton - VS Professional Sub'
  tenantsJson: '${{ convertToJson(parameters.tenants) }}'
  uniqueSuffix: 'qpe'
  acrName: 'acr$(appName)$(uniqueSuffix)'
  rgName: 'rg-$(appName)'
  aksName: 'aks-$(appName)'
  aksWorkloadIdentityServiceAccountName: 'sa-workload-identity-$(appName)'
  aksNamespace: 'default'
  kvName: 'kv-$(appName)-$(uniqueSuffix)'

  rgAksNodesName: 'rg-k8s-$(appName)'
  aksFederatedIdentityName: 'fic-$(aksName)'
  aksWorkloadIdentityName: 'aks-$(appName)'
  aksNodeCount: 1
  aksVmSize: 'Standard_B2s'
  tfStateResourceGroup: 'rg-terraform'
  tfStateStorageAccount: 'terraformstateakssample'
  tfStateContainerName: 'tfstate'
  tfStateFileName: 'terraform.tfstate'

  appVersion: "0.1.1"
  imageName: 'aksworkloadidentitysampleapi'
  imageTag: '$(appVersion)'
  aksWorkloadIdentityClientId: '{dynamic}'
  aksPvcBlobName: 'azure-blob'
  aksStorageClassBlobName: 'azureblob-nfs-standard'
  helmChartDescription: 'AKS Sample App'
  helmReleaseName: 'aks-sample'
  helmChartName: 'aks-sample'  
  helmChartVersion: '0.6.1'
  helmAppVersion: '$(appVersion)'