name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
  repositories:
  - repository: self
  pipelines:
  - pipeline: build_and_package # Name of the pipeline resource.
    source: Aks.App.BuildAndPackage.Poc # The name of the pipeline referenced by this pipeline resource.
    trigger: true 
  
parameters:
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true

variables: 
  - template: ../Templates/variables/root.yml   

stages:
- template: ../Templates/stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'dev'
    apply: ${{ parameters.apply }}
    dependsOn: []