name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
- repo: self

parameters:
- name: tenantsAll
  displayName: 'Tenants'
  type: object
  default:
    - name: tenant1
      region: au1
      env: dev
      ring: stable
    - name: tenant2
      region: au1
      env: dev
      ring: vnext

- name: rings
  displayName: 'Deployment Rings'
  type: object
  default: 
    - name: stable
      region: au1
      env: dev
      version: "0.3.0"
    - name: vnext
      region: au1
      env: dev
      version: "0.3.0"

- name: imageBuildTag
  displayName: 'Image Build Tag'
  type: string
  default: "0.3.0"

variables:
- template: ../../Common/Templates/variables/root.yml  
  parameters:
    tenantsAll: ${{ parameters.tenantsAll }} 

stages:
- template: ../Templates/stage.yml
  parameters:
    svcConnAzureRm: 'Keith Patton - VS Professional Sub'
    region: 'au1'
    env: 'dev'
    dependsOn: []
    rings: ${{ parameters.rings }}
    imageBuildTag: ${{ parameters.imageBuildTag }}