name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
- repo: self

parameters:
- name: tenants
  displayName: 'Tenants'
  type: object
  default:
    - name: tenant1
      group: common
      region: au1
      env: dev
      ring: stable
    - name: tenant2
      group: common2
      region: au1
      env: dev
      ring: latest  

- name: rings
  displayName: 'Deployment Rings'
  type: object
  default: 
    - name: stable
      region: au1
      env: dev
      version: "0.3.0"
    - name: latest
      region: au1
      env: dev
      version: "0.3.0"


- name: imageBuild
  displayName: 'Build and Push Images'
  type: boolean
  default: true
- name: imageBuildTag
  displayName: 'App Image Build Tag'
  type: string
  default: "0.3.0"
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true

stages:
- template: ../Templates/stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    tenants: ${{ parameters.tenants }}
    region: 'au1'
    env: 'dev'
    dependsOn: []
    rings: ${{ parameters.rings }}
    imageBuild: ${{ parameters.imageBuild }}
    imageBuildTag: ${{ parameters.imageBuildTag }}
    apply: ${{ parameters.apply }}