trigger:
  branches:
    include:
      - master
  paths:
    include:
      - AksSample.Job/**
      - AksWorkloadIdentitySample.Api/**

resources:
- repo: self

variables: 
  - template: ../Templates/variables/root.yml 

stages:
- stage: package
  displayName: Build and Push Images
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - job: package
    displayName: Build and Push Images
    steps:
      - checkout: self
        fetchDepth: 0
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: "5.6.11"
      - task: gitversion/execute@0
        displayName: Determine Version
        env:
          DOTNET_ROLL_FORWARD: "Major"
      - task: Docker@2
        displayName: Build App Image
        inputs:
          command: build
          repository: $(imageName)
          dockerfile: '$(Build.SourcesDirectory)/AksWorkloadIdentitySample.Api/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: |
            $(GitVersion.SemVer)
      - task: Docker@2
        displayName: Build Job Init Image
        inputs:
          command: build
          repository: "$(jobInitImageName)"
          dockerfile: '$(Build.SourcesDirectory)/AksSample.Job/Dockerfile'
          buildContext: '$(Build.SourcesDirectory)'
          tags: |
            $(GitVersion.SemVer)
      - task: AzureCLI@2
        displayName: 'Push Images'
        inputs:
          azureSubscription: $(svcConnAzureRmDefault)
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az acr login --name $(acrName)
            # push app image
            docker tag $(imageName):$(GitVersion.SemVer) $(acrName).azurecr.io/$(imageName):$(GitVersion.SemVer)
            docker push $(acrName).azurecr.io/$(imageName):$(GitVersion.SemVer)
            # push job init
            docker tag $(jobInitImageName):$(GitVersion.SemVer) $(acrName).azurecr.io/$(jobInitImageName):$(GitVersion.SemVer)
            docker push $(acrName).azurecr.io/$(jobInitImageName):$(GitVersion.SemVer)             



