name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
- repo: self

variables: 
  - template: ../Templates/variables/root.yml 
  - name: acrName
    value: acrau1dev01 # Hard coded because build is not regional

stages:
- stage: BuildPackage
  displayName: Build and Package
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - deployment: Image
    displayName: Build and Package
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - task: gitversion/setup@0
            displayName: Install GitVersion
            inputs:
              versionSpec: "5.6.11"
          - task: gitversion/execute@0
            displayName: Determine Version
            env:
              DOTNET_ROLL_FORWARD: "Major"
          - script: |
              echo '##vso[task.setvariable variable=semVer;isOutput=true]$(GitVersion.SemVer)'
              echo $(GitVersion.SemVer)            
          - task: Docker@2
            displayName: Build App Image
            inputs:
              command: build
              repository: $(imageName)
              dockerfile: '$(Build.SourcesDirectory)/AksWorkloadIdentitySample.Api/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: |
                $(semVer)
          - task: Docker@2
            displayName: Build Job Init Image
            inputs:
              command: build
              repository: "$(jobInitImageName)"
              dockerfile: '$(Build.SourcesDirectory)/AksSample.Job/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: |
                $(semVer)
          - task: AzureCLI@2
            displayName: 'Push Images'
            inputs:
              azureSubscription: ${{ parameters.svcConnAzureRm}}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az acr login --name $(acrName)
                # push app image
                docker tag $(imageName):$(semVer) $(acrName).azurecr.io/$(imageName):$(semVer)
                docker push $(acrName).azurecr.io/$(imageName):$(semVer)
                # push job init
                docker tag $(jobInitImageName):$(semVer) $(acrName).azurecr.io/$(jobInitImageName):$(semVer)
                docker push $(acrName).azurecr.io/$(jobInitImageName):$(semVer)               