name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

variables: 
  - name: buildBranch
    value: 'test'
  - template: templates/variables/root.yml   

parameters:
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true
- name: channel
  displayName: Deployment Channel
  type: string
  default: internal
  values:
    - internal
    - live

resources:
  
  repositories:
  - repository: self

  pipelines:
  - pipeline: build_and_package # Name of the pipeline resource.
    source: Aks.App.BuildPackage.Poc # The name of the pipeline referenced by this pipeline resource.
    trigger: none 
  
  containers:
    - container: webapi # e.g. core api
      type: acr
      ${{ if eq(resources.pipelines.build_and_package.sourceVersion, 'refs/heads/master') }}:
        azureSubscription: 'Keith Patton - VS Professional Sub'
        resourceGroup: rg-common
        registry: acrcommon01
        repository: webapi        
      ${{ else }}:
        azureSubscription: 'Keith Patton - VS Professional Sub2'
        resourceGroup: rg-common2
        registry: acrcommon02
        repository: webapi 
    # - container: webapi-init-job  # e.g. core job
    #   type: acr
    #   ${{ if eq(parameters['channel'], 'internal') }}:
    #     azureSubscription: 'Keith Patton - VS Professional Sub'
    #     resourceGroup: rg-common
    #     registry: acrcommon01
    #     repository: webapi-init-job        
    #   ${{ else }}:
    #     azureSubscription: 'Keith Patton - VS Professional Sub2'
    #     resourceGroup: rg-common2
    #     registry: acrcommon02
    #     repository: webapi-init-job 

stages:
- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'dev'
    apply: ${{ parameters.apply }}
    dependsOn: []

- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'qa'
    apply: ${{ parameters.apply }}
    dependsOn: au1_dev