name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

variables: 
  - template: templates/variables/root.yml   

parameters:
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true

resources:
  
  repositories:
  - repository: self

  pipelines:
  - pipeline: build_and_package # Name of the pipeline resource.
    source: Aks.App.BuildPackage.Poc # The name of the pipeline referenced by this pipeline resource.
    trigger: none 
  
  containers:
    - container: webapi-init-job-internal
      type: acr
      repository: webapi
      azureSubscription: 'Keith Patton - VS Professional Sub'
      resourceGroup: rg-common
      registry: acrcommon01
    - container: webapi-init-job-live
      type: acr
      repository: webapi
      azureSubscription: 'Keith Patton - VS Professional Sub'
      resourceGroup: rg-common
      registry: acrcommon01

stages:
- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'dev'
    apply: ${{ parameters.apply }}
    dependsOn: []

- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'qa'
    apply: ${{ parameters.apply }}
    dependsOn: au1_dev