name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none



parameters:
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true
- name: containerRegistry
  displayName: Container Resources Registry
  type: string
  default: internal
  values:
    - internal
    - live

variables: 
  - template: templates/variables/root.yml  
  - template: templates/variables/acr-pipeline-resources.yml
    parameters:
      registry: ${{ parameters.containerRegistry }}   

resources:
  
  repositories:
  - repository: self

  pipelines:
  - pipeline: build_and_package # Name of the pipeline resource.
    source: Aks.App.BuildPackage.Poc # The name of the pipeline referenced by this pipeline resource.
    trigger: none 
  
  containers:
    - container: webapi-init-job
      type: acr
      repository: webapi-init-job
      azureSubscription: 'Keith Patton - VS Professional Sub'
      resourceGroup: $(rgAcrName)
      registry: $(acrName)

stages:
- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'dev'
    apply: ${{ parameters.apply }}
    dependsOn: []

- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'qa'
    apply: ${{ parameters.apply }}
    dependsOn: au1_dev