name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
  repositories:
  - repository: self
  pipelines:
  - pipeline: build_and_package # Name of the pipeline resource.
    source: Aks.App.BuildPackage.Poc # The name of the pipeline referenced by this pipeline resource.
    trigger: true 
  
  containers:
    - container: webapi-init-job
      type: acr
      azureSubscription: ${{ if(eq('test', 'refs/heads/master'), 'Keith Patton - VS Professional Sub', 'Keith Patton - VS Professional Sub') }}
      resourceGroup: rg-common
      registry: acrcommon01
      repository: webapi-init-job

parameters:
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true

variables: 
  - template: templates/variables/root.yml   

stages:
- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'dev'
    apply: ${{ parameters.apply }}
    dependsOn: []

- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'qa'
    apply: ${{ parameters.apply }}
    dependsOn: au1_dev