name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

variables: 
  - name: buildBranch
    value: 'test'
  - template: templates/variables/root.yml   

parameters:
- name: apply
  displayName: 'Apply Infra'
  type: boolean
  default: true
- name: registry
  displayName: Container Registry
  type: string
  default: internal
  values:
    - internal
    - live

resources:
  
  repositories:
  - repository: self

  pipelines:
  - pipeline: build_and_package # Name of the pipeline resource.
    source: Aks.App.BuildPackage.Poc # The name of the pipeline referenced by this pipeline resource.
    trigger: true 
  
  containers:
    - container: webapi-init-job
      type: acr
      ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
        azureSubscription: 'Keith Patton - VS Professional Sub'
        resourceGroup: rg-common
        registry: acrcommon01
        repository: webapi-init-job        
      ${{ else }}:
        azureSubscription: 'Keith Patton - VS Professional Sub2'
        resourceGroup: rg-common2
        registry: acrcommon02
        repository: webapi-init-job 
        #repository: webapi-init-job

# resources.pipelines.build_and_package.sourceBranch


stages:
- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'dev'
    apply: ${{ parameters.apply }}
    dependsOn: []

- template: templates/stages/reg-env-stage.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'qa'
    apply: ${{ parameters.apply }}
    dependsOn: au1_dev