name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
- repo: self

parameters:
- name: tenants
  displayName: 'Tenants'
  type: object
  default:
    - name: tenant1
      group: common
      region: au1
      env: dev
      ring: stable
    - name: tenant2
      group: common2
      region: au1
      env: dev
      ring: latest  

stages:
- template: ../Templates/stage-teardown.yml
  parameters:
    svcConnAzureRm: 'Keith Patton - VS Professional Sub'    
    tenants: ${{ parameters.tenants }}
    region: 'au1'
    env: 'dev'
    dependsOn: []