name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
- repo: self

variables: 
  - template: Templates/Variables/root.yml   

stages:

- template: Templates/reg-env-stage-teardown.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'dev'
    dependsOn: []

- template: Templates/reg-env-stage-teardown.yml
  parameters:
    svcConnAzureRm: $(svcConnAzureRmDefault)
    region: 'au1'
    env: 'qa'
    dependsOn: []