acrName: acrau1dev01
aksPvcName: azure-blob
aksManagedIdentities: [{"client_id":"daee9da8-e7aa-46ec-8235-7369c87f2620","name":"aks-au1-dev-webapi-common"},{"client_id":"b5e21f6b-3f64-40d7-8a31-5967da49c77b","name":"aks-au1-dev-webapi-common2"},{"client_id":"e5e21f6b-3f64-40d7-8a31-5967da49c77b","name":"aks-au1-dev-webapi-default"}]

aksStorageClassNamePrefix: webapi-azureblob-nfs-standard-
aksStorageClassSkuName: Standard_ZRS
aksWorkloadIdentityServiceAccountName: sa-workload-identity-webapi
aksWorkloadIdentityNameDefaultSuffix: "default"
appName: webapi
imageName: webapi
jobInitImageName: "webapi-init-job"
jobInitImageVersion: "1.0.0"

kvName: kv-au1-dev-01
rings: [
  {
    "name": "stable",
    "region": "au1",
    "env": "dev",
    "version": "0.3.0"
  },
  {
    "name": "latest",
    "region": "au1",
    "env": "dev",
    "version": "0.3.0"
  }
]
groups: [{
    "name": "common",
    "region": "au1",
    "env": "dev",
    "cpu": "1",
    "memory": "1Gi",
    "pods": "1",
    "requestsCpu": "500m",
    "requestsMemory": "500Mi",
    "limitsCpu": "1",
    "limitsMemory": "1Gi"
  },
  {
    "name": "common",
    "region": "au1",
    "env": "qa",
    "cpu": "1",
    "memory": "1Gi",
    "pods": "1",
    "requestsCpu": "500m",
    "requestsMemory": "500Mi",
    "limitsCpu": "1",
    "limitsMemory": "1Gi"
  }]
sqlServerName: sql-au1-dev-01
tenants: [{"name":"tenant1","group":"common","region":"au1","env":"dev","ring":"stable"},{"name":"tenant2","group":"common2","region":"au1","env":"dev","ring":"latest"}]
traefikAksNamespace: traefik