# Performs Terraform Destroy for Azure Resource Manager
# Note: Assumes tf backend variables are set

parameters:
- name: svcConnAzureRm
  type: string
- name: workingDirectory
  type: string

steps:
- task: TerraformTaskV3@3
  displayName: Terraform Destroy
  inputs:
    provider: 'azurerm'
    environmentServiceNameAzureRM: ${{ parameters.svcConnAzureRm}}
    command: 'destroy'
    commandOptions: '--auto-approve'
    workingDirectory: '${{ parameters.workingDirectory}}'
    backendAzureRmResourceGroupName: $(tfStateResourceGroup)
    backendAzureRmStorageAccountName: $(tfStateStorageAccount)
    backendAzureRmContainerName: $(tfStateContainerName)
    backendAzureRmKey: $(tfStateFileName)