# Ensures that the Azure Storage Account and Container are created if necessary for backend state
# Note: Assumes tf backend variables and location are set

parameters:
- name: svcConnAzureRm
  type: string

steps:
- task: AzureCLI@2
  displayName: 'Ensure Terraform State Storage Account and Container'
  inputs:
    azureSubscription: ${{ parameters.svcConnAzureRm}}
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --location $(location) --name $(tfStateResourceGroup)
      az storage account create -n $(tfStateStorageAccount) -g $(tfStateResourceGroup) -l $(location) --sku Standard_LRS --encryption-services blob
      az storage container create -n $(tfStateContainerName) --account-name $(tfStateStorageAccount) -g $(tfStateResourceGroup)