# Set dynamic vars for region and environment
# Sets $ringsJson vars to represent active rings
# Sets $groupsJson vars to represent active groups
# Sets $tenantsJson vars to represent active tenants
# Note: loads from data json files

parameters:
- name: region
  type: string
- name: env
  type: string
- name: groupsDataFilePath
  type: string
- name: ringsDataFilePath
  type: string  
- name: tenantsScriptFilePath
  type: string
  default: "@()"  
- name: tenantsDataPaths
  type: string
  default: "@()"
- name: tenantsRequiredData
  type: string
  default: "@()"

steps:
- template: vars-replace-tokens.yml
  parameters:
    targetFiles: |
      $(groupsDataFilePath)
      $(ringsDataFilePath)
- task: Bash@3
  displayName: 'Sets Groups and Rings Vars for ${{ parameters.region }}_${{ parameters.env }}'
  inputs:
    targetType: 'inline'
    script: |
      region=$(echo "${{parameters.region}}")
      env=$(echo "${{parameters.env}}")
      
      # Load rings data from file path
      ringsJson=$(cat ${{ parameters.ringsDataFilePath }} | jq -c --arg region "$region" --arg env "$env" '[.[] | select(.region == $region) | select(.env == $env)]')
      echo "##vso[task.setvariable variable=ringsJson;]$ringsJson"
      echo "Stage Rings:"
      echo $ringsJson

      # Load groups data from file path
      groupsJson=$(cat ${{ parameters.groupsDataFilePath }} | jq -c --arg region "$region" --arg env "$env" '[.[] | select(.region == $region) | select(.env == $env)]')
      echo "##vso[task.setvariable variable=groupsJson;]$groupsJson"
      echo "Stage Groups:"
      echo $groupsJson

  - task: PowerShell@2
    displayName: 'Sets Tenants Json Var for ${{ parameters.region }}_${{ parameters.env }}'
    inputs:
      filePath: '${{ parameters.tenantsScriptFilePath }}'
      arguments: '-reg ${{ parameters.region }} -env ${{ parameters.env }} -tenantsDataPaths ${{ parameters.tenantsDataPaths }} -requiredData ${{ parameters.tenantsRequiredData }}'