parameters:
- name: region
  displayName: 'Region'
  type: string
- name: env
  displayName: 'Environment'
  type: string
variables:
  - name: imageName
    value: '$(appName)'
  - name: aksPvcBlobName
    value: 'azure-blob'
  - name: aksStorageClassBlobName
    value: 'azureblob-nfs-standard'
  - name: webapiChartDescription 
    value: 'AKS Sample App'
  - name: webapiReleaseName
    value: 'webapi'
  - name: webapiChartName
    value: 'webapi'  
  - name: webapiChartVersion
    value: '0.7.2'
  - name: webapiSharedReleaseName # delete if possible
    value: 'webapi-shared'
  - name: webapiSharedChartName
    value: 'webapi-shared'  
  - name: webapiSharedChartVersion
    value: $(webapiChartVersion)   
  - name: webapiSharedChartDescription 
    value: 'AKS Sample App Shared Components' 