variables:
- name: appName
  value: "webapi"
- name: imageName
  value: "$(appName)"
- name: jobInitImageName
  value: "$(appName)-init-job"
- name: svcConnAzureRmDefault
  value: 'Keith Patton - VS Professional Sub'  