variables:
- template: ../../../Common/Templates/variables/root.yml 
- name: appName
  value: "webapi"
- name: tenants
  value: |-
    [{
      "name": "tenant1",
      "group": "common",
      "region": "au1",
      "env": "dev",
      "ring": "latest"
    }, {
      "name": "tenant1",
      "group": "common",
      "region": "au1",
      "env": "qa",
      "ring": "latest"
    }, {  
      "name": "tenant2",
      "group": "common2",
      "region": "au1",
      "env": "dev",
      "ring": "latest"
    }, {
      "name": "tenant2",
      "group": "common2",
      "region": "au1",
      "env": "qa",
      "ring": "latest"
    }]
- name: rings
  value: |-
    [{
      "name": "latest",
      "region": "au1",
      "env": "dev",
      "version": "$(buildVersion)"
    }, {
      "name": "latest",
      "region": "au1",
      "env": "qa",
      "version": "$(buildVersion)"
    }]
  # build pipeline resource sets run name to version using GitVersion
- name: buildVersion
  value: $(resources.pipeline.build_and_package.runName)
- name: imageName
  value: "$(appName)"
- name: jobInitImageName
  value: "$(appName)-init-job"
- name: jobInitImageVersion
  value: $(buildVersion)