parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev
- name: imageBuildTag
  displayName: 'Image Build Tag'
  type: string
variables:
  - name: imageName
    value: '$(appName)'
  - name: imageBuildTag
    value: '${{ parameters.imageBuildTag }}'
  - name: aksWorkloadIdentityClientId
    value: '{dynamic}'
  - name: aksPvcBlobName
    value: 'azure-blob'
  - name: aksStorageClassBlobName
    value: 'azureblob-nfs-standard'
  - name: webapiChartDescription 
    value: 'AKS Sample App'
  - name: webapiReleaseName
    value: 'webapi'
  - name: webapiChartName
    value: 'webapi'  
  - name: webapiChartVersion
    value: '0.7.2'
  - name: webapiSharedReleaseName
    value: 'webapi-shared'
  - name: webapiSharedChartName
    value: 'webapi-shared'  
  - name: webapiSharedChartVersion
    value: '0.1.0'   
  - name: webapiSharedChartDescription 
    value: 'AKS Sample App Shared Components' 