imageName: #{imageName}#
imageTag: #{imageTag}#
tenants: #{tenantsJson}#
storageClassBlobName: #{aksStorageClassBlobName}#
pvcBlobName: #{aksPvcBlobName}#
aksNamespace: #{aksNamespace}#
workloadIdentityServiceAccountName: #{aksWorkloadIdentityServiceAccountName}#
workloadIdentityClientId: #{aksWorkloadIdentityClientId}#
keyVaultName: #{kvName}#
azureContainerRegistryName: #{acrName}#
sqlServerName: #${sqlServerName}#