apiVersion: v1
{{- range $.Values.rings }}
kind: Service
metadata:
  name: webapi-{{ .name }}
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
  selector:
    app: webapi-{{ .name }}
{{- end }}