parameters:
- name: region
  displayName: 'Region'
  type: string
- name: env
  displayName: 'Environment'
  type: string

variables:
- template: reg_${{ parameters.region }}.yml 
- template: env_${{ parameters.env }}.yml  
- template: reg_${{ parameters.region }}-env_${{ parameters.env }}.yml  

- name: TF_LOG
  value: WARNING

- name: appName
  value: 'aksdemo'
- name: rgName
  value: 'rg-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: acrName
  value: 'acr${{ parameters.region }}${{ parameters.env }}$(appName)$(uniqueSuffix)'
- name: kvName
  value: 'kv-${{ parameters.region }}-${{ parameters.env }}-$(appName)-$(uniqueSuffix)'
- name: aksName
  value: 'aks-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: aksNamespace
  value: 'default'
- name: aksStorageAccountName
  value: 'stg${{ parameters.region }}${{ parameters.env }}$(appName)aks'
- name: aksWorkloadIdentityName
  value: 'aks-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: aksWorkloadIdentityServiceAccountName
  value: 'sa-workload-identity-${{ parameters.region }}-${{ parameters.env }}-$(appName)'
- name: sqlServerName
  value: 'sql-${{ parameters.region }}-${{ parameters.env }}-$(uniqueSuffix)'