
# config map for each ring within per namespaced tenant group 

{{- $groupRings := (uniq (seq (index .Values.tenants) "group" "ring")) -}}
{{- range $groupRings }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.appName }}-{{ .ring }}
  namespace: {{ $.Values.appName }}-{{ .group }}
data:
  aks_keyvault: {{ $.Values.kvName }}
  sql_server_name: {{ $.Values.sqlServerName }}
  app_version: {{ $.Values.appVersion }}
---
{{- end }}