
# config map for each ring within per namespaced tenant group 
{{- $rings := list }}
{{- range $.Values.rings }}
  {{- if not (has .name $rings) }}
  {{- $rings = append $rings .name}}
  {{- end }}
{{- end }}

{{- range $.Values.groups }}
  {{- $group := .name }}
  {{- range $rings }}
    {{- $ring := .}}
    {{- $ringVersion := "" }}
    {{- range $.Values.rings }}
      {{- if eq $ring .name }}
        {{- $ringVersion = .version }}
      {{- end }}
    {{- end }} 
    {{- $configMapNamespace := printf "%s-%s" $.Values.appName $group }}
    {{- $configMapName := printf "%s-%s" $.Values.appName $ring }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  namespace: {{ $configMapNamespace }}
  labels:
    name: {{ $configMapName }}
    group: {{ $group }}
    ring: {{ $ring }}
    {{- range $.Values.tenants }}
      {{- if and (eq $ring .ring) (eq $group .group)  }}
    tenant-{{ .name }}: {{ .name }}
      {{- end }}
    {{- end }}  
data:
  aks_keyvault: {{ $.Values.kvName }}
  sql_server_name: {{ $.Values.sqlServerName }}
  tenant_group: {{ $group }}
  app_version: {{ $ringVersion }}
---
  {{- end }}
{{- end }}