
# config map for each ring within per namespaced tenant group 
{{- $groups := list }}
{{- range $.Values.tenants }}
  {{- if not (has .group $groups) }}
  {{- $groups = append $groups .group}}
  {{- end }}
{{- end }}

{{- $rings := list }}
{{- range $.Values.rings }}
  {{- if not (has .name $rings) }}
  {{- $rings = append $rings .name}}
  {{- end }}
{{- end }}

{{- range $groups }}
  {{- $group := .}}
  {{- range $rings }}
    {{- $ring := .}}
    {{- $ringVersion := "" }}
    {{- range $.Values.rings }}
      {{- if eq $ring .name }}
        {{- $ringVersion = .version }}
      {{- end }}
    {{- end }} 
    {{- $configMapNamespace := printf "%s-%s" $.Values.appName $group }}
    {{- $configMapName := printf "%s-%s" $.Values.appName $ring }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  namespace: {{ $configMapNamespace }}
data:
  aks_keyvault: {{ $.Values.kvName }}
  sql_server_name: {{ $.Values.sqlServerName }}
  tenant_group: {{ $group }}
  app_version: {{ $ringVersion }}
---
  {{- end }}
{{- end }}