# deployment for each ring per namespaced tenant group 

{{- $groupRings := (uniq (seq (index .Values.tenants) "group" "ring")) -}}
{{- range $groupRings  }}
  {{- $group := .group }}
  {{- $ring := .ring }}
  {{- $ringVersion := "" }}
  {{- range $.Values.rings }}
    {{- if eq $ring .name }}
      {{- $ringVersion = .version }}
      {{- break }}
    {{- end }}
  {{- end }}  
  {{- $deploymentNamespace := printf "%s-%s" $.Values.appName .group }}
  {{- $deploymentName := printf "%s-%s" $.Values.appName .ring }}
  {{- $serviceName := $deploymentName }}
  {{- $configMapName := $deploymentName }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  namespace: {{ $deploymentNamespace }}
  labels:
    app: {{ $deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $deploymentName }}
        azure.workload.identity/use: "true"
        service: {{ $serviceName }}
    spec:
      serviceAccountName: {{ $.Values.aksWorkloadIdentityServiceAccountName }}
      containers:
        - name: {{ $deploymentName }}
          image: {{ $.Values.acrName }}.azurecr.io/{{ $.Values.imageName }}:{{ $ringVersion }}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ $configMapName }}
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
          volumeMounts:
            - mountPath: /var/common
              name: common
              {{- range $.Values.tenants }}
                # only tenants in current group
                {{- if eq $group .group }}
            - mountPath: /var/{{ .name }}
              name: {{ .name }}
                {{- end }}
              {{- end }}
      volumes:
        - name: common
          persistentVolumeClaim:
             claimName: {{ $.Values.aksPvcName }}        
          {{- range $.Values.tenants }}
          # only tenants in current group
            {{- if eq $group .group }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ $.Values.aksPvcName }}-{{ .name }}
            {{- end }}
          {{- end }}
---
{{- end }}