# deployment for each ring per namespaced tenant group 

{{- $rings := list }}
{{- range $.Values.rings }}
  {{- if not (has .name $rings) }}
  {{- $rings = append $rings .name}}
  {{- end }}
{{- end }}

{{- range $.Values.groups }}
  {{- $group := . }}
  {{- range $rings }}
    {{- $ring := .}}
    {{- $ringVersion := "" }}
    {{- range $.Values.rings }}
      {{- if eq $ring .name }}
        {{- $ringVersion = .version }}
      {{- end }}
    {{- end }}    
    {{- $deploymentNamespace := printf "%s-%s" $.Values.appName $group.name }}
    {{- $deploymentName := printf "%s-%s" $.Values.appName $ring }}
    {{- $configMapName := $deploymentName }}
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  namespace: {{ $deploymentNamespace }}
  labels:
    app: {{ $deploymentName }}
    group: {{ $group.name }}
    ring: {{ $ring }}    
    {{- range $.Values.tenants }}
      {{- if and (eq $ring .ring) (eq $group.name .group)  }}
    tenant-{{ .name }}: {{ .name }}
      {{- end }}
    {{- end }}
spec:
  replicas: {{ $group.replicas }}
  selector:
    matchLabels:
      app: {{ $deploymentName }}
  template:
    metadata:
      annotations:
        azure.workload.identity/inject-proxy-sidecar: true
      labels:
        app: {{ $deploymentName }}
        azure.workload.identity/use: "true"
        group: {{ $group.name }}
        ring: {{ $ring }}
        {{- range $.Values.tenants }}
          {{- if and (eq $ring .ring) (eq $group.name .group)  }}
        tenant-{{ .name }}: {{ .name }}
          {{- end }}
        {{- end }}        
    spec:
      serviceAccountName: {{ $.Values.aksWorkloadIdentityServiceAccountName }}
      containers:
        - name: {{ $deploymentName }}
          image: {{ $.Values.acrName }}.azurecr.io/{{ $.Values.imageName }}:{{ $ringVersion }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: {{ $group.limitsCpuPod }}
              memory: {{ $group.limitsMemoryPod }}
            requests:
              cpu: {{ $group.cpuPod }}
              memory: {{ $group.memoryPod }}
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ $configMapName }}
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
          volumeMounts:
            - mountPath: /var/common
              name: common
              {{- range $.Values.tenants }}
                {{- if eq $group.name .group }}
            - mountPath: /var/{{ .name }}
              name: {{ .name }}
                {{- end }}
              {{- end }}
      volumes:
        - name: common
          persistentVolumeClaim:
             claimName: {{ $.Values.aksPvcName }}        
          {{- range $.Values.tenants }}
            {{- if eq $group.name .group }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ $.Values.aksPvcName }}-{{ .name }}
            {{- end }}
          {{- end }}
---
  {{- end }}
{{- end }}