# job run before install/upgrade

{{- $jobName := printf "%s-%s" $.Values.appName "init-job"}}
{{- $jobNamespace := printf "%s-%s" $.Values.appName $.Values.jobsAksNamespaceSuffix }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  namespace: {{ $jobNamespace }}
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  parallelism: {{ len .Values.tenants }}
  completions: {{ len .Values.tenants }}
  template:
    metadata:
      name: {{ $jobName }}
      namespace: {{ $jobNamespace }}
    spec:
      restartPolicy: Never
      containers:
        {{- range .Values.tenants }}
      - name: "{{ .name }}-init-job"
        image: {{ $.Values.acrName }}.azurecr.io/{{ $.Values.jobInitImageName }}:{{ $.Values.jobInitImageVersion}}
        imagePullPolicy: Always
        env:
        - name: TENANT
          value: "{{ .name }}"
        - name: WAIT_FOR
          value: "{{ $.Values.jobInitWaitFor }}"
        {{- end }}
---