# job run for each tenant before install/upgrade

{{- range .Values.tenants }}
  {{- $tenant := .name }}
  {{- $jobName := printf "%s-job" $tenant }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ $jobName }}
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrations
        image: {{ $.Values.acrName }}.azurecr.io/{{ $.Values.jobInitImageName }}:{{ $.Values.jobInitImageVersion}}
        imagePullPolicy: Always
      env:
      - name: TENANT
        value: {{ $tenant }}
      - name: WAIT_FOR
        value: {{ $.Values.jobInitWaitFor }}        
---
{{- end }}