# namespace for each namespaced tenant group 

{{- $groups := list }}
{{- range $.Values.tenants }}
  {{- if not (has .group $groups) }}
  {{- $groups = append $groups .group}}
  {{- end }}
{{- end }}

{{- range $groups }}
  {{- $group := .}}
  {{- $name := printf "%s-%s" $.Values.appName . }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    name: {{ $name }}
    {{- range $.Values.tenants }}
      {{- if eq $group .group  }}
    tenant: {{ .name }}
      {{- end }}
    {{- end }}    
---
{{- end }}