# namespace for each namespaced tenant group 
{{- range $.Values.groups }}
  {{- $group := .name }}
  {{- $name := printf "%s-%s" $.Values.appName $group }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ $name }}
    group: {{ $group }}
    {{- range $.Values.tenants }}
      {{- if eq $group .group  }}
    tenant-{{ .name }}: {{ .name }}
      {{- end }}
    {{- end }}    
---
{{- end }}


# namespace for app level jobs work

{{- $jobsNamespace := printf "%s-%s" $.Values.appName "jobs" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $jobsNamespace  }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    name: {{ $jobsNamespace  }}             
---