# network policy for each namespaced tenant group 
# ingress: disallow traffic between tenant groups and allow only for traefik, default
# egress: allow all by default  

{{- $groups := list }}
{{- range $.Values.tenants }}
  {{- if not (has .group $groups) }}
  {{- $groups = append $groups .group}}
  {{- end }}
{{- end }}

{{- range $group := $groups }}
  {{- $namespace := (printf "%s-%s" $.Values.appName $group)}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $namespace }}-group-isolation
  namespace: {{ $namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: default
    - namespaceSelector:
        matchLabels:
          name: {{ $.Values.traefikAksNamespace }}
    - namespaceSelector:
        matchLabels:
          name: {{ $namespace }}                    
  egress:
  - {}
---
{{- end }}