# network policy for each namespaced tenant group 
# ingress: disallow traffic between tenant groups and allow only for traefik, default
# egress: allow all by default  

{{- $groups := list }}
{{- range $.Values.tenants }}
  {{- if not (has .group $groups) }}
  {{- $groups = append $groups .group}}
  {{- end }}
{{- end }}

{{- range $group := $groups }}
  {{- $networkPolicyNamespace := (printf "%s-%s" $.Values.appName $group)}}
  {{- $networkPolicyName := (printf "%s-%s" $networkPolicyNamespace "group-isolation")}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $networkPolicyName }}
  namespace: {{ $networkPolicyNamespace }}
  labels:
    name: {{ $networkPolicyName }}
    {{- range $.Values.tenants }}
      {{- if (eq $group .group)  }}
    tenant: {{ .name }}
      {{- end }}
    {{- end }}    
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: default
    - namespaceSelector:
        matchLabels:
          name: {{ $.Values.traefikAksNamespace }}
    - namespaceSelector:
        matchLabels:
          name: {{ $networkPolicyNamespace }}                    
  egress:
  - {}
---
{{- end }}