# pvcs 
{{- $groups := list }}
{{- range $.Values.tenants }}
  {{- if not (has .group $groups) }}
  {{- $groups = append $groups .group}}
  {{- end }}
{{- end }}

# pvc per namespaced tenant group 
{{- range $groups }}
  {{- $storageClassName := printf "%s-%s" $.Values.aksStorageClassNamePrefix "common" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.aksPvcName }}
  namespace: {{ $.Values.appName }}-{{ . }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ $storageClassName }}
  resources:
    requests:
      storage: 5Gi
---
{{- end }}

# pvc for each tenant per namespaced tenant group 
{{- range $.Values.tenants }}
  {{- $pvcName := printf "%s-%s" $.Values.aksPvcName .name }}
  {{- $pvcNamespace := printf "%s-%s" $.Values.appName .group }}
  {{- $storageClassName := printf "%s%s" $.Values.aksStorageClassNamePrefix .name }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  namespace: {{ $pvcNamespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ $storageClassName }}
  resources:
    requests:
      storage: 5Gi
---
{{- end }}