# pvcs 

{{- $storageClassNamePrefix := .Values.storageClassNamePrefix }}

# pvc per namespaced tenant group 
{{- $groups := make(map[string]bool) }}
{{- range .Values.tenants }}
  {{- if !$groups.{{.group}} }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.aksPvcName }}
  namespace: {{ .Values.appName }}-{{ .group }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ storageClassNamePrefix }}common
  resources:
    requests:
      storage: 5Gi
---
---
  {{- end }}
{{- end }}

# pvc for each tenant per namespaced tenant group 
{{- range .Values.tenants }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.aksPvcName }}-{{ .name }}
  namespace: {{ .Values.appName }}-{{ .group }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ storageClassNamePrefix }}{{ .name}}
  resources:
    requests:
      storage: 5Gi
---
{{- end }}