# pvcs 

{{- $storageClassNamePrefix := $.Values.aksStorageClassNamePrefix }}

# pvc per namespaced tenant group 
{{- $groups := (uniq (seq (index .Values.tenants) .group)) -}}
{{- range $groups }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.aksPvcName }}
  namespace: {{ .Values.appName }}-{{ . }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ storageClassNamePrefix }}common
  resources:
    requests:
      storage: 5Gi
---
{{- end }}

# pvc for each tenant per namespaced tenant group 
{{- range .Values.tenants }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.aksPvcName }}-{{ .name }}
  namespace: {{ .Values.appName }}-{{ .group }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ storageClassNamePrefix }}{{ .name}}
  resources:
    requests:
      storage: 5Gi
---
{{- end }}