# resource quota for each namespaced tenant group 

{{- range $.Values.groups }}
  {{- $group := .}}
  {{- $name := printf "%s-%s" $.Values.appName $group.name }}
  {{- $namespace := $name }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name:  {{ $name }}
  namespace: {{ $namespace }}
  labels:
    name: {{ $name }}
    group: {{ $group.name }}
    {{- range $.Values.tenants }}
      {{- if eq $group.name .group  }}
    tenant-{{ .name }}: {{ .name }}
      {{- end }}
    {{- end }}      
spec:
  hard:
    cpu: {{- $group.cpu }}
    memory: {{- $group.memory }}
    pods: {{- $group.pods }}
    requests.cpu: {{- $group.requestsCpu }}
    requests.memory: {{- $group.requestsMemory }}
    limits.cpu: {{- $group.limitsCpu }}
    limits.memory: {{- $group.limitsMemory }}
---
{{- end }}