# resource quota for each namespaced tenant group 

{{- range $.Values.groups }}
  {{- $group := .}}
  {{- $name := printf "%s-%s" $.Values.appName $group.name }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name:  {{ $name }}
spec:
  hard:
    cpu: {{- $group.cpu }}
    memory: {{- $group.memory }}
    pods: {{- $group.pods }}
    requests.cpu: {{- $group.requestsCpu }}
    requests.memory: {{- $group.requestsMemory }}
    limits.cpu: {{- $group.limitsCpu }}
    limits.memory: {{- $group.limitsMemory }}
---
{{- end }}