# service account per namespaced tenant group using managed identity

{{- $groups := list }}
{{- range $.Values.tenants }}
  {{- if not (has .group $groups) }}
  {{- $groups = append $groups .group}}
  {{- end }}
{{- end }}
{{- range $groups }}
  {{- $group := .}}
  {{- $saNamespace := printf "%s-%s" $.Values.appName . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- range $.Values.aksManagedIdentities }}
      {{- if hasSuffix (printf "-%s" $group) .name }}
    azure.workload.identity/client-id: {{ .client_id }}
      {{- end }}
    {{- end }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ $.Values.aksWorkloadIdentityServiceAccountName }}
  namespace: {{ $saNamespace }}
---
{{- end }}

# service account for app jobs using managed identity

{{- $name := printf "%s-%s" $.Values.appName $.Values.jobsAksNamespaceSuffix }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- range $.Values.aksManagedIdentities }}
      {{- if hasSuffix (printf "-%s" $.Values.jobsAksNamespaceSuffix) .name }}
    azure.workload.identity/client-id: {{ .client_id }}
      {{- end }}
    {{- end }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ $.Values.aksWorkloadIdentityServiceAccountName }}
  namespace: {{ $saNamespace }}
---