# service account per namespaced tenant group using managed identity

{{- range $.Values.groups }}
  {{- $group := .name }}
  {{- $saNamespace := printf "%s-%s" $.Values.appName $group }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.aksWorkloadIdentityServiceAccountName }}
  namespace: {{ $saNamespace }}
  annotations:
    {{- range $.Values.aksManagedIdentities }}
      {{- if hasSuffix (printf "-%s" $group) .name }}
    azure.workload.identity/client-id: {{ .client_id }}
      {{- end }}
    {{- end }}
  labels:
    azure.workload.identity/use: "true"
    group: {{ $group }}
    {{- range $.Values.tenants }}
      {{- if (eq $group .group)  }}
    tenant-{{ .name }}: {{ .name }}
      {{- end }}    
    {{- end }}   
---
{{- end }}

# service account for app level work using managed identities
# note: placed within the release namespace

{{- $saNamespace := $.Values.appName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.aksWorkloadIdentityServiceAccountName }}
  namespace: {{ $saNamespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- range $.Values.aksManagedIdentities }}
      {{- if hasSuffix (printf "-%s" $.Values.aksWorkloadIdentityNameDefaultSuffix) .name }}
    azure.workload.identity/client-id: {{ .client_id }}
      {{- end }}
    {{- end }}
  labels:
    azure.workload.identity/use: "true"   
    {{- range $.Values.tenants }}
    tenant-{{ .name }}: {{ .name }}
    {{- end }}               
---