# service for each ring per namespaced tenant group 

{{- $groupRings := (uniq (seq (index .Values.tenants) "group" "ring")) -}}
{{- range $groupRings }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.appName }}-{{ .ring }}
  namespace: {{ $.Values.appName }}-{{ .group }}
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
  selector:
    app: {{ $.Values.appName }}-{{ .ring }}
---
{{- end }}