# cluster wide resources, not namespaced

# common blob container for app
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $.Values.aksStorageClassNamePrefix }}common
provisioner: blob.csi.azure.com
parameters:
  skuName: {{ $.Values.aksStorageClassSkuName }}
  containerName: common
  protocol: nfs
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
# tenanted storage class containers for each tenant for app
{{- range .Values.tenants }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $.Values.aksStorageClassNamePrefix }}{{ .name }}
provisioner: blob.csi.azure.com
parameters:
  skuName: {{ $.Values.aksStorageClassSkuName }}
  containerName: {{ .name }}
  protocol: nfs
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: true
---
{{- end }}