parameters:
- name: svcConnAzureRm
  type: string  
- name: region
  type: string
- name: env
  type: string
- name: dependsOn  
  type: object

stages:
- stage: common
  displayName: common
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - deployment: Infrastructure
    displayName: Destroy Common Infra Resources
    # all environments manually enabled by authorised person on first run 
    environment: common
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true               
          - template: ../../../../common/templates/steps/vars-replace-tokens.yml
            parameters:
              targetFiles: |
                devops/infra/terraform/common/variables.tf                                    
          - template: ../../../../common/templates/steps/tf-init-az.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/devops/infra/terraform/common'
          - template: ../../../../common/templates/steps/tf-destroy-az.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/devops/infra/terraform/common'