parameters:
- name: svcConnAzureRm
  type: string  
- name: region
  type: string
- name: env
  type: string
- name: dependsOn  
  type: object

stages:
- stage: ${{ parameters.region }}_${{ parameters.env }}
  displayName: ${{ parameters.region }}_${{ parameters.env }}
  variables: 
    - template: ../variables/reg-env.yml 
      parameters:
        region: ${{ parameters.region }}
        env: ${{ parameters.env }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - deployment: Infrastructure
    displayName: Ensure ${{ parameters.region }}_${{ parameters.env }} Infra Resources
    # all environments manually enabled by authorised person on first run 
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true              
          - task: AzureCLI@2
            displayName: 'Enable Workload Identity Preview (One Time)'
            condition: eq(1,2)
            inputs:
              azureSubscription: ${{ parameters.svcConnAzureRm}}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az extension add --name aks-preview
                az feature register --namespace "Microsoft.ContainerService" --name "EnableWorkloadIdentityPreview"
                az provider register --namespace Microsoft.ContainerService
          - template: ../../../../common/templates/steps/tf-state-az.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
          - template: ../../../../common/templates/steps/vars-replace-tokens.yml
            parameters:
              targetFiles: |
                devops/infra/terraform/regenv/variables.tf          
          - template: ../../../../common/templates/steps/tf-init-az.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/devops/infra/terraform/regenv'
          - template: ../../../../common/templates/steps/tf-apply-az.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/devops/infra/terraform/regenv'
  - deployment: InfrastructureApps    
    displayName: Deploy ${{ parameters.region }}_${{ parameters.env }} Infra Apps
    dependsOn: Infrastructure
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - template: ../../../../common/templates/steps/vars-replace-tokens.yml
            parameters:
              targetFiles: |
                devops/infra/helm/**/Chart.yaml
                devops/infra/helm/**/values.yaml
          - template: ../../../../common/templates/steps/helm-upgrade.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              releaseName: $(traefikReleaseName)
              chartPath: '$(System.DefaultWorkingDirectory)/devops/infra/helm/traefik'    
              namespace: $(traefikAksNamespace)