parameters:
- name: registry
  type: string
  values:
    - internal
    - live

variables:
  ${{ if eq(parameters['registry'], 'internal') }}:     
    acrAzureSubscription: 'Keith Patton - VS Professional Sub'
    azrResourceGroup: rg-common
    acrName: acrcommon01
  ${{ else }}:
    acrAzureSubscription: 'Keith Patton - VS Professional Sub'
    azrResourceGroup: rg-common
    acrName: acrcommon01