# App Specific Variables for Region and Environment

parameters:
- name: region
  displayName: 'Region'
  type: string
- name: env
  displayName: 'Environment'
  type: string

variables:

- template: ../../../../common/templates/variables/reg-env.yml
  parameters:
    region: "${{ parameters.region }}"
    env: "${{ parameters.env }}"
  
- name: aksFederatedIdentityNamePrefix
  value: "fic-${{ parameters.region }}-${{ parameters.env }}-$(aksNamespacePrefix)"
- name: aksWorkloadIdentityNamePrefix
  value: "aks-${{ parameters.region }}-${{ parameters.env }}-$(aksNamespacePrefix)"
- name: aksWorkloadIdentityNameDefaultSuffix
  value: "default"