variables:
- template: ../../../../common/templates/variables/root.yml 
- name: appName
  value: "webapi"
- name: tenantsDataPaths
  value: '@("$(Build.SourcesDirectory)/devops/app/data/tenants")'
- name: tenantsRequiredData
  value: '@("group","ring")'
- name: rings
  value: |-
    [{
      "name": "latest",
      "region": "au1",
      "env": "dev",
      "version": "$(buildVersion)"
    }, {
      "name": "latest",
      "region": "au1",
      "env": "qa",
      "version": "$(buildVersion)"
    }]
- name: groups
  value: |-
    '[{
      "name": "common",
      "region": "au1",
      "env": "dev",
      "cpu": "1",
      "memory": "1Gi",
      "pods": "1",
      "requestsCpu": "500m",
      "requestsMemory": "500Mi",
      "limitsCpu": "1",
      "limitsMemory": "1Gi"
    },
    {
      "name": "common",
      "region": "au1",
      "env": "qa",
      "cpu": "1",
      "memory": "1Gi",
      "pods": "1",
      "requestsCpu": "500m",
      "requestsMemory": "500Mi",
      "limitsCpu": "1",
      "limitsMemory": "1Gi"
    }]'
  # build pipeline resource sets run name to version using GitVersion
- name: buildVersion
  value: $(resources.pipeline.build_and_package.runName)
- name: imageName
  value: "$(appName)"
- name: jobInitImageName
  value: "$(appName)-init-job"
- name: jobInitImageVersion
  value: $(buildVersion)