variables:
- template: ../../../../common/templates/variables/root.yml 
- name: appName
  value: "webapi"
- name: tenantsDataPaths
  value: '@("$(Build.SourcesDirectory)/Devops/App/data/tenants")'
- name: tenantsRequiredData
  value: '@("group","ring")'
- name: rings
  value: |-
    [{
      "name": "latest",
      "region": "au1",
      "env": "dev",
      "version": "$(buildVersion)"
    }, {
      "name": "latest",
      "region": "au1",
      "env": "qa",
      "version": "$(buildVersion)"
    }]
  # build pipeline resource sets run name to version using GitVersion
- name: buildVersion
  value: $(resources.pipeline.build_and_package.runName)
- name: imageName
  value: "$(appName)"
- name: jobInitImageName
  value: "$(appName)-init-job"
- name: jobInitImageVersion
  value: $(buildVersion)
