parameters:
- name: svcConnAzureRm
  type: string
- name: region
  type: string
- name: env
  type: string
- name: dependsOn  
  type: object

stages:
- stage: ${{ parameters.region }}_${{ parameters.env }}
  displayName: ${{ parameters.region }}_${{ parameters.env }}
  variables: 
    - template: ../../Common/Templates/variables/reg-env.yml 
      parameters:
        region: ${{ parameters.region }}
        env: ${{ parameters.env }}  
    - template: variables/reg-env.yml 
      parameters:
        region: ${{ parameters.region }}
        env: ${{ parameters.env }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - deployment: Infrastructure
    displayName: Ensure Shared Infra Resources
    # for security reasons all environments must be provisioned by authorised person in advance
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true              
          - task: replacetokens@5
            displayName: 'Replace tokens with variables'
            inputs:
              targetFiles: |
                Devops/Infra/Terraform/variables.tf
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'warn'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true   
              verbosity: 'detailed'                     
          - task: TerraformTaskV3@3
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              backendServiceArm: ${{ parameters.svcConnAzureRm}}
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/Infra/Terraform'
              backendAzureRmResourceGroupName: $(tfStateResourceGroup)
              backendAzureRmStorageAccountName: $(tfStateStorageAccount)
              backendAzureRmContainerName: $(tfStateContainerName)
              backendAzureRmKey: $(tfStateFileName)                               
          - task: TerraformTaskV3@3
            displayName: Terraform Destroy
            inputs:
              provider: 'azurerm'
              environmentServiceNameAzureRM: ${{ parameters.svcConnAzureRm}}
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/Infra/Terraform'
              commandOptions: '--auto-approve'
              backendAzureRmResourceGroupName: $(tfStateResourceGroup)
              backendAzureRmStorageAccountName: $(tfStateStorageAccount)
              backendAzureRmContainerName: $(tfStateContainerName)
              backendAzureRmKey: $(tfStateFileName)