parameters:
- name: svcConnAzureRm
  type: string
- name: region
  type: string
- name: env
  type: string
- name: dependsOn  
  type: object

stages:
- stage: ${{ parameters.region }}_${{ parameters.env }}
  displayName: ${{ parameters.region }}_${{ parameters.env }}
  variables: 
    - template: ../../Common/Templates/variables/reg-env.yml 
      parameters:
        region: ${{ parameters.region }}
        env: ${{ parameters.env }}  
    - template: variables/reg-env.yml 
      parameters:
        region: ${{ parameters.region }}
        env: ${{ parameters.env }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ubuntu-latest 
  jobs:
  - deployment: Infrastructure
    displayName: Ensure Shared Infra Resources
    # all environments manually enabled by authorised person on first run 
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true              
          - task: AzureCLI@2
            displayName: 'Enable Workload Identity Preview (One Time)'
            condition: eq(1,2)
            inputs:
              azureSubscription: ${{ parameters.svcConnAzureRm}}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az extension add --name aks-preview
                az feature register --namespace "Microsoft.ContainerService" --name "EnableWorkloadIdentityPreview"
                az provider register --namespace Microsoft.ContainerService
          - template: ../../Common/Templates/tfStateAzStg.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
          - template: ../../Common/Templates/replaceTokens.yml
            parameters:
              targetFiles: |
                Devops/Infra/Terraform/variables.tf          
          - template: ../../Common/Templates/tfInitAzRm.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/Infra/Terraform'
          - template: ../../Common/Templates/tfApplyAzRm.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              workingDirectory: '$(System.DefaultWorkingDirectory)/Devops/Infra/Terraform'
  - deployment: InfrastructureApps    
    displayName: Deploy Shared Infra Apps
    dependsOn: Infrastructure
    environment: ${{ parameters.region }}_${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true   
          - template: ../../Common/Templates/replaceTokens.yml
            parameters:
              targetFiles: |
                Devops/Infra/Helm/**/Chart.yaml
                Devops/Infra/Helm/**/values.yaml
          - template: ../../Common/Templates/helmUpgrade.yml
            parameters:
              svcConnAzureRm: ${{ parameters.svcConnAzureRm }}
              releaseName: $(traefikReleaseName)
              chartPath: '$(System.DefaultWorkingDirectory)/Devops/Infra/Helm/traefik'    
              namespace: $(traefikAksNamespace)