parameters:
- name: region
  displayName: 'Region'
  type: string
  values:
  - au1
  default: au1
- name: env
  displayName: 'Environment'
  type: string
  values:
  - dev

variables:
  rgAksNodesName: '$(rgName)-k8s'
  aksFederatedIdentityName: 'fic-${{ parameters.region }}-${{ parameters.env }}-$(aksName)'
  aksNodeCount: 1
  aksVmSize: 'Standard_B2s'
  sqlServerName: "sql-${{ parameters.region }}-${{ parameters.env }}-$(uniqueSuffix)"
  sqlElasticPoolName: "elp-${{ parameters.region }}-${{ parameters.env }}-$(uniqueSuffix)"
  sqlAdAdminUsername: "keith.d.patton@vista.co"
  sqlAdminUsername: "sql-admin"

  tfStateResourceGroup: 'rg-${{ parameters.region }}-${{ parameters.env }}-terraform'
  tfStateStorageAccount: 'stg${{ parameters.region }}${{ parameters.env }}tfstate'
  tfStateContainerName: 'tfstate'
  tfStateFileName: 'terraform.tfstate'