variables:
  rgAksNodesName: 'rg-k8s-$(appName)'
  aksFederatedIdentityName: 'fic-$(aksName)'
  aksNodeCount: 1
  aksVmSize: 'Standard_B2s'
  tfDestroyBeforeApply: false
  tfStateResourceGroup: 'rg-terraform'
  tfStateStorageAccount: 'terraformstateakssample'
  tfStateContainerName: 'tfstate'
  tfStateFileName: 'terraform.tfstate'